def Content():

    page_dict = {   "Java": [["Introduction", "/Java/introduction/", "introduction"],
                            ["Syntax", "/Java/syntax/", "syntax"],
                            ["Comments", "/Java/comments/", "comments"],
                            ["Objects and Classes", "/Java/objects_classes/", "objects_classes"],
                            ["Variables", "/Java/variables/", "variables"],
                            ["Data Structures", "/Java/data_structures/", "data_structures"],
                            ["Modifiers", "/Java/modifiers/", "modifiers"],
                            ["Operators", "/Java/operators/", "operators"],
                            ["Loop Control", "/Java/loop_control/", "loop_control"],
                            ["Decision Making", "/Java/decision_making/", "decision_making"],
                            ["Imports", "/Java/imports/", "imports"],
                            ["Files & I/O", "/Java/files_io/", "files_io"],
                            ["Exceptions", "/Java/exceptions/", "exceptions"],
                            ["Final Thoughts", "/Java/final_thoughts/", "final_thoughts"],],
              "C_PlusPlus": [["Introduction", "/C_plusplus/introduction/", "introduction"],
                            ["Syntax", "/C_plusplus/syntax/", "syntax"],
                            ["Comments", "/C_plusplus/comments/", "comments"],
                            ["Objects and Classes", "/C_plusplus/objects_classes/", "objects_classes"],
                            ["Variables", "/C_plusplus/variables/", "variables"],
                            ["Data Structures", "/C_plusplus/data_structures/", "data_structures"],
                            ["Modifiers", "/C_plusplus/modifiers/", "modifiers"],
                            ["Operators", "/C_plusplus/operators/", "operators"],
                            ["Loop Control", "/C_plusplus/loop_control/", "loop_control"],
                            ["Decision Making", "/C_plusplus/decision_making/", "decision_making"],
                            ["Imports", "/C_plusplus/imports/", "imports"],
                            ["Files & I/O", "/C_plusplus/files_io/", "files_io"],
                            ["Exceptions", "/C_plusplus/exceptions/", "exceptions"],
                            ["Final Thoughts", "/C_plusplus/final_thoughts/", "final_thoughts"],],
                 "C_Sharp": [["Introduction I", "/C_sharp/introduction/","introduction"],
                            ["Introduction II", "/C_sharp/introduction2/","introduction2"],
                            ["Syntax", "/C_sharp/syntax/", "syntax"],
                            ["Comments", "/C_sharp/comments/", "comments"],
                            ["Objects and Classes", "/C_sharp/objects_classes/", "objects_classes"],
                            ["Variables", "/C_sharp/variables/", "variables"],
                            ["Data Structures", "/C_sharp/data_structures/", "data_structures"],
                            ["Modifiers", "/C_sharp/modifiers/", "modifiers"],
                            ["Operators", "/C_sharp/operators/", "operators"],
                            ["Loop Control", "/C_sharp/loop_control/", "loop_control"],
                            ["Decision Making", "/C_sharp/decision_making/", "decision_making"],
                            ["Imports", "/C_sharp/imports/", "imports"],
                            ["Files & I/O", "/C_sharp/files_io/", "files_io"],
                            ["Exceptions", "/C_sharp/exceptions/", "exceptions"],
                            ["Final Thoughts", "/C_sharp/final_thoughts/", "final_thoughts"],],
                  "Python": [["Introduction", "/Python/introduction/", "introduction"],
                            ["Syntax", "/Python/syntax/", "syntax"],
                            ["Comments", "/Python/comments/", "comments"],
                            ["Data Types", "/Python/data_types/", "data_types"],
                            ["Variables", "/Python/variables/", "variables"],
                            ["Operators", "/Python/operators/", "operators"],
                            ["Decision Making", "/Python/decision_making/", "decision_making"],
                            ["Loop Control", "/Python/loop_control/", "loop_control"],
                            ["Functions", "/Python/functions/", "functions"],
                            ["Objects and Classes", "/Python/objects_classes/", "objects_classes"],
                            ["Data Structures", "/Python/data_structures/", "data_structures"],
                            ["Imports", "/Python/imports/", "imports"],
                            ["Files & I/O", "/Python/files_io/", "files_io"],
                            ["Exceptions", "/Python/exceptions/", "exceptions"],
                            ["Final Thoughts", "/Python/final_thoughts/", "final_thoughts"],],
                     "SQL": [["Introduction", "/SQL/introduction/", "introduction"],
                            ["Syntax", "/SQL/syntax/", "syntax"],],
              "Javascript": [["Introduction", "/Javascript/introduction/", "introduction"],
                            ["Installation", "/Javascript/installation/", "installation"],
                            ["Output", "/Javascript/output/", "output"],
                            ["Syntax", "/Javascript/syntax/", "syntax"],
                            ["Statements", "/Javascript/statements/", "statements"],
                            ["Comments", "/Javascript/comments/", "comments"],
                            ["Variables", "/Javascript/variables/", "variables"],
                            ["Operators", "/Javascript/operators/", "operators"],
                            ["Arithmetic", "/Javascript/arithmetic/", "arithmetic"],
                            ["Assignment", "/Javascript/assignment/", "assignment"],
                            ["Data Types", "/Javascript/data_types/", "data_types"],
                            ["Functions", "/Javascript/functions/", "functions"],
                            ["Objects", "/Javascript/objects/", "objects"],
                            ["Scope", "/Javascript/scope/", "scope"],
                            ["Events", "/Javascript/events/", "events"],
                            ["Strings", "/Javascript/strings/", "strings"],
                            ["String Methods", "/Javascript/string_methods/", "string_methods"],
                            ["Numbers", "/Javascript/numbers/", "numbers"],
                            ["Number Methods", "/Javascript/number_methods/", "number_methods"],
                            ["Math", "/Javascript/math/", "math"],],
               "AngularJS": [["Introduction", "/AngularJS/introduction/", "introduction"],
                            ["Environment", "/AngularJS/environment/", "environment"],
                            ["MVC Architecture", "/AngularJS/architecture/", "architecture"],
                            ["Expressions", "/AngularJS/expressions/", "expressions"],],
                    "HTML": [["Introduction", "/HTML/introduction/", "introduction"]],
                }
    return page_dict

